openapi: "3.0.2"
info:
  title: KLAY OPEN API
  version: "1.10.0"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:7151

paths:
  /personal/lockAccount:
    post:
      operationId: lockAccount
      summary: "[lockAccount]"
      description: |
        Removes the private key with a given address from memory. The account can no longer be used to send transactions.

        | Client | Method invocation |
        |-----|-----|
        | Console   | personal.lockAccount(address) |
        | RPC | {"method": "personal_lockAccount", "params": [address]} |

        **JSONRPC:** `personal_lockAccount`
      tags:
        - personal

      parameters:
        - name: address
          required: true
          schema:
            type: string
          description: The account address to lock.
          in: query

      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "../../components/requests/JsonRpcRequest.yaml#/components/schemas/JsonRpcRequest"
                - type: object
                  properties:
                    method:
                      type: string
                      default: "personal_lockAccount"
                    params:
                      type: array
                      items:
                        title: address
                        type: string
                      description: "The account address to lock."
                      example: ["0xfa415bb3e6231f488ff39eb2897db0ef3636dd32"]

      responses:
        200:
          description: Return the locked status of the account.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../components/responses/JsonRpcResponse.yaml#/components/schemas/JsonRpcResponse"
                  - type: object
                    properties:
                      result:
                        type: boolean
                        example: true
      
      x-codeSamples:
        - lang: "curl"
          label: "Curl"
          source:
            $ref: "../../code-samples/curl/personal/lockAccounts.sh"
        # - lang: "java"
        #   label: "Java"
        #   source:
        #     $ref: ""
        # - lang: "javascript"
        #   label: "Javascript"
        #   source:
        #    $ref: ""
        # - lang: "python"
        #   label: "Python"
        #   source:
        #     $ref: ""