openapi: "3.0.2"
info:
  title: KLAY OPEN API
  version: "1.10.0"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:7151

paths:
  /klay/getTransactionBySenderTxHash:
    post:
      operationId: klayGetTransactionBySenderTxHash
      summary: "[getTransactionBySenderTxHash] Returns the information about a transaction requested by sender transaction hash."
      description: |
        Returns the information about a transaction requested by sender transaction hash. This API works only on RPC call, not on JavaScript console. Please note that this API returns correct result only if indexing feature is enabled by --sendertxhashindexing. This can be checked by call klay_isSenderTxHashIndexingEnabled.
        
        **JSONRPC:** `klay_getTransactionBySenderTxHash`

      tags:
        - klay.transaction

      parameters:
        - name: transactionHash
          required: true
          schema:
            type: string
            format: 32-byte DATA
          description: Hash of a transaction that is signed only by the sender.
          in: query

      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "../../../components/requests/JsonRpcRequest.yaml#/components/schemas/JsonRpcRequest"
                - $ref: "../../../components/schemas/klay/transaction/GetTransactionBySenderTxHash.yaml#/components/schemas/KlayGetTransactionBySenderTxHashReq"

      responses:
        200:
          description: Returns information about a transaction by block number and transaction index position.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../../components/responses/JsonRpcResponse.yaml#/components/schemas/JsonRpcResponse"
                  - $ref: "../../../components/schemas/klay/transaction/GetTransactionBySenderTxHash.yaml#/components/schemas/KlayGetTransactionBySenderTxHashResp"

      externalDocs:
        url: https://docs.klaytn.foundation/content/dapp/json-rpc/api-references/klay/transaction#klay_gettransactionbysendertxhash
        description: Klaytn Docs
      x-codeSamples:
#        - lang: "curl"
#          label: "Curl"
#          source:
#            $ref: "../../../code-samples/curl/klay/transaction/getTransactionByBlockNumberAndIndex.sh"
        # - lang: "java"
        #   label: "Java"
        #   source:
        #     $ref: ""
        #- lang: "javascript"
        #  label: "Javascript"
        #  source:
        #    $ref: ""
        #- lang: "python"
        #  label: "Python"
        #  source:
        #    $ref: ""
