openapi: "3.0.2"
info:
  title: Klay Open API
  version: "1.10.0"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:7151

paths:
  /eth/sendTransaction:
    post:
      summary: "[sendTransaction]"
      tags:
        - eth
      operationId: sendTransaction
      description: |
        Constructs a transaction with given parameters, signs the transaction with a sender's private key and propagates the transaction to Klaytn network.
        
        NOTE: The address to sign with must be unlocked.
        
        **JSONRPC:** `eth_sendTransaction`

      parameters:
        - name: transactionArgs
          in: query
          description: An object of transaction arguments. See the table below for the object's properties.
          required: true
          schema:
            $ref: "../../../components/schemas/common/Common.yaml#/components/schemas/TransactionArgs"

      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "../../../components/requests/JsonRpcRequest.yaml#/components/schemas/JsonRpcRequest"
                - $ref: "#/components/schemas/KlaySendTransactionReq"

      responses:
        200:
          description: Return the transaction hash or the zero hash if the transaction is not yet available.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../../components/responses/JsonRpcResponse.yaml#/components/schemas/JsonRpcResponse"
                  - $ref: "#/components/schemas/KlaySendTransactionResp"

      x-codeSamples:
        - lang: "curl"
          label: "Curl"
          source:
            $ref: "../../../code-samples/curl/eth/transaction/sendTransaction.sh"
#        - lang: "java"
#          label: "Java"
#          source:
#            $ref: "../../../code-samples/java/src/main/java/opensdk/sdk/apis/eth/transaction/EthCallExample.java"
#        - lang: "javascript"
#          label: "Javascript"
#          source:
#            $ref: "../../../code-samples/javascript/eth/transaction/call.js"
#        - lang: "python"
#          label: "Python"
#          source:
#            $ref: "../../../code-samples/python/eth/transaction/call.py"

components:
  schemas:
    KlaySendTransactionReq:
      type: object
      required:
        - method
      properties:
        method:
          type: string
          default: 'eth_sendTransaction'
        params:
          type: array
          items:
              $ref: "../../../components/schemas/common/Common.yaml#/components/schemas/TransactionArgs"

    KlaySendTransactionResp:
      type: object
      properties:
        result:
          type: string
          format: 32-byte DATA
          description: The transaction hash or the zero hash if the transaction is not yet available.
          example: "0xe670ec64341771606e55d6b4ca35a1a6b75ee3d5145a99d05921026d1527331"

