openapi: "3.0.2"
info:
  title: KLAY OPEN API
  version: "1.10.0"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:7151

paths:
  /klay/feeHistory:
    post:
      operationId: feeHistory
      summary: "[feeHistory] Returns base fee per gas and transaction effective priority fee per gas history for the requested block range if available.d"
      description: |
        Returns base fee per gas and transaction effective priority fee per gas history for the requested block range if available.

        **JSONRPC:** `klay_feeHistory`

        **NOTE:** This API is effective after Klaytn v1.8.0
      tags:
        - klay

      parameters:
        - name: blockCount
          required: true
          schema:
            $ref: "#/components/schemas/BlockCount"
          description: Number of blocks in the requested range in hexadecimal. Between 1 (0x1) and 1024 (0x400) blocks can be requested in a single query. Less than requested may be returned if not all blocks are available.
          in: query
        - name: lastBlock
          in: query
          description: Highest numbered block of the requested range as block number or block tag.
          required: true
          schema:
            $ref: "../../../components/schemas/common/Common.yaml#/components/schemas/BlockNumberOrTag"
        - name: rewardPercentiles
          required: true
          schema:
            $ref: "#/components/schemas/RewardPercentiles"
          description: An array of floating point values between 0 and 100.
          in: query

      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "../../../components/requests/JsonRpcRequest.yaml#/components/schemas/JsonRpcRequest"
                - $ref: "#/components/schemas/KlayFeeHistoryReq"

      responses:
        200:
          description: Returns base fee per gas and transaction effective priority fee per gas history for the requested block range if available.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../../components/responses/JsonRpcResponse.yaml#/components/schemas/JsonRpcResponse"
                  - $ref: "#/components/schemas/KlayFeeHistoryResp"
      externalDocs:
        url: https://docs.klaytn.foundation/content/dapp/json-rpc/api-references/klay/gas#klay_feehistory
        description: Klaytn Docs
      x-codeSamples:
        - lang: "curl"
          label: "Curl"
          source:
            $ref: "../../../code-samples/curl/klay/gas/feeHistory.sh"
        # - lang: "java"
        #   label: "Java"
        #   source:
        #     $ref: ""
        #- lang: "javascript"
        #  label: "Javascript"
        #  source:
        #    $ref: ""
        #- lang: "python"
        #  label: "Python"
        #  source:
        #    $ref: ""

components:
  schemas:
    KlayFeeHistoryReq:
      type: object
      required:
        - method
        - params
      properties:
        method:
          type: string
          default: 'klay_feeHistory'
        params:
          type: array
          items:
            anyOf:
              - $ref: "#/components/schemas/BlockCount"
              - $ref: "../../../components/schemas/common/Common.yaml#/components/schemas/BlockNumberOrTag"
              - $ref: "#/components/schemas/RewardPercentiles"
          example:  ["0x10", "latest", [0.1, 0.2, 0.3]]

    BlockCount:
      type: string
      format: Hexadecimal
      description: Number of blocks in the requested range in hexadecimal. Between 1 (0x1) and 1024 (0x400) blocks can be requested in a single query. Less than requested may be returned if not all blocks are available.

    RewardPercentiles:
      type: array
      items:
        type: number
        format: float
      description: An array of floating point values between 0 and 100.

    KlayFeeHistoryResp:
        type: object
        required:
            - oldestBlock
            - baseFeePerGas
            - gasUsedRatio
            - reward
        properties:
            result:
              type: object
              properties:
                oldestBlock:
                  type: string
                  format: Hexadecimal
                  description: Lowest numbered block of the returned range in hexadecimal.
                baseFeePerGas:
                  type: array
                  items:
                    type: string
                    format: Hexadecimal
                  description: An array of block base fees per gas. This includes the next block after the newest of the returned range, because this value can be derived from the newest block.
                gasUsedRatio:
                  type: array
                  items:
                    type: number
                    format: float
                  description: An array of the ratios of gas used per block. These are calculated as the ratio of gasUsed and gasLimit.
                reward:
                  type: array
                  items:
                    type: array
                    items:
                      type: string
                      format: Hexadecimal
                  description: An array of effective priority fee per gas data points from a single block. All zeroes are returned if the block is empty.
              example:
                {
                  "oldestBlock": "0xa5b",
                  "reward": [
                    [ "0x0", "0x0", "0x0" ],
                    [ "0x5d21dba00", "0x5d21dba00", "0x5d21dba00" ]
                  ],
                  "baseFeePerGas": [ "0x0", ..., "0x0" ],
                  "gasUsedRatio": [ 0, ..., 0.0002963777000002964 ]
                }
