openapi: "3.0.2"
info:
  title: Klay Open API
  version: "1.10.0"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:7151

paths:
  /debug/writeMutexProfile:
    post:
      summary: "[writeMutexProfile]"
      tags:
        - debug
      operationId: writeMutexProfile
      description: |
        Writes a goroutine blocking profile to the given file.

        **JSONRPC:** `debug_writeMutexProfile`

      parameters:
        - name: file
          in: query
          description: The filename for the profiling output.
          required: true
          schema:
            type: string

      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "../../../components/requests/JsonRpcRequest.yaml#/components/schemas/JsonRpcRequest"
                - $ref: "#/components/schemas/DebugWriteMutexProfileReq"

      responses:
        200:
          description: Writes a goroutine blocking profile to the given file.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../../components/responses/JsonRpcResponse.yaml#/components/schemas/JsonRpcResponse"
                  - $ref: "#/components/schemas/DebugWriteMutexProfileResp"

      x-codeSamples:
        - lang: "curl"
          label: "Curl"
          source:
            $ref: "../../../code-samples/curl/klaytnDebug/profiling/writeMutexProfile.sh"
#        - lang: "java"
#          label: "Java"
#          source:
#            $ref: "../../../code-samples/java/src/main/java/opensdk/sdk/apis/eth/account/EthAccountsExample.java"
#        - lang: "javascript"
#          label: "Javascript"
#          source:
#            $ref: "../../../code-samples/javascript/eth/account/accounts.js"
#        - lang: "python"
#          label: "Python"
#          source:
#            $ref: "../../../code-samples/python/eth/account/accounts.py"

components:
  schemas:
    DebugWriteMutexProfileReq:
      type: object
      properties:
        method:
          type: string
          default: debug_writeMutexProfile
        params:
          type: array
          items:
            title: File
            type: string
            description: The filename for the profiling output.
          example: ["mem.profile"]

    DebugWriteMutexProfileResp:
      type: object
      properties:
        result:
          type: string
          example: null