openapi: "3.0.2"
info:
  title: Klay Open API
  version: "1.10.0"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:7151

paths:
  /eth/coinbase:
    post:
      summary: "[coinbase] Returns the client coinbase address."
      tags:
        - eth
      operationId: coinbase
      description: |
        Returns the client coinbase address.

        **JSONRPC:** `eth_coinbase`

      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "../../../components/requests/JsonRpcRequest.yaml#/components/schemas/JsonRpcRequest"
                - $ref: "#/components/schemas/CoinbaseReq"

      responses:
        200:
          description: The current coinbase address.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../../components/responses/JsonRpcResponse.yaml#/components/schemas/JsonRpcResponse"
                  - $ref: "#/components/schemas/CoinbaseResp"

      externalDocs:
        url: https://docs.klaytn.foundation/content/dapp/json-rpc/api-references/eth/config#eth_coinbase
        description: Klaytn Docs
      x-codeSamples:
        - lang: "curl"
          label: "Curl"
          source:
            $ref: "../../../code-samples/curl/eth/config/coinbase.sh"
        # - lang: "java"
        #   label: "Java"
        #   source:
        #     $ref: ""
        # - lang: "javascript"
        #   label: "Javascript"
        #   source:
        #     $ref: "../../../code-samples/javascript/eth/transaction/coinbase.js"
        # - lang: "python"
        #   label: "Python"
        #   source:
        #     $ref: "../../../code-samples/python/eth/transaction/coinbase.py"

components:
  schemas:
    CoinbaseReq:
      type: object
      required:
        - method
      properties:
        method:
          type: string
          default: 'eth_coinbase'

    CoinbaseResp:
      type: object
      properties:
        result:
          type: string
          format: 20-byte DATA
          description: The current coinbase address.
          example: "0xc94770007dda54cF92009BFF0dE90c06F603a09f"
