openapi: 3.0.2
info:
  title: KLAYTN OPEN API
  version: 1.10.0
  contact:
    name: API support
    url: https://forum.klaytn.foundation/
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
tags:
  - name: mainbridge
    description: API for mainbridge namespace
servers:
  - url: http://localhost:7151
  - url: https://api.baobab.klaytn.net:8651
  - url: https://public-en-cypress.klaytn.net
paths:
  /mainbridge/getChildChainIndexingEnabled:
    post:
      summary: '[getChildChainIndexingEnabled]'
      tags:
        - mainbridge
      operationId: getChildChainIndexingEnabled
      description: |
        mainbridge_getChildChainIndexingEnabled returns if indexing anchoring transaction is enabled or not.

        **JSONRPC:** `mainbridge_getChildChainIndexingEnabled`
      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/JsonRpcRequest'
                - $ref: '#/components/schemas/MainbridgeGetChildChainIndexingEnabledReq'
      responses:
        '200':
          description: mainbridge_getChildChainIndexingEnabled returns if indexing anchoring transaction is enabled or not.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/JsonRpcResponse'
                  - $ref: '#/components/schemas/MainbridgeGetChildChainIndexingEnabledResp'
      x-codeSamples:
        - lang: curl
          label: Curl
          source: |
            curl -X 'POST' \
              'https://api.baobab.klaytn.net:8651/mainbridge/getChildChainIndexingEnabled' \
              -H 'accept: application/json' \
              -H 'Content-Type: application/json' \
              -d '{
              "method": "mainbridge_getChildChainIndexingEnabled",
              "id": 1,
              "jsonrpc": "2.0",
              "params": []
            }'
  /mainbridge/nodeInfo:
    post:
      summary: '[nodeInfo]'
      tags:
        - mainbridge
      operationId: nodeInfo
      description: |
        Returns bridge node information including the KNI (Klaytn Network Identifier) of the node. A mainbridge node can connect to a subbrige node via the KNI.

        **JSONRPC:** `mainbridge_nodeInfo`
      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/JsonRpcRequest'
                - $ref: '#/components/schemas/MainbridgeNodeInfoReq'
      responses:
        '200':
          description: Returns bridge node information including the KNI (Klaytn Network Identifier) of the node.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/JsonRpcResponse'
                  - $ref: '#/components/schemas/MainbridgeNodeInfoResp'
      x-codeSamples:
        - lang: curl
          label: Curl
          source: |
            curl -X 'POST' \
              'https://api.baobab.klaytn.net:8651/mainbridge/nodeInfo' \
              -H 'accept: application/json' \
              -H 'Content-Type: application/json' \
              -d '{
              "method": "mainbridge_nodeInfo",
              "id": 1,
              "jsonrpc": "2.0",
              "params": []
            }'
  /mainbridge/convertChildChainBlockHashToParentChainTxHash:
    post:
      summary: '[convertChildChainBlockHashToParentChainTxHash]'
      tags:
        - mainbridge
      operationId: convertChildChainBlockHashToParentChainTxHash
      description: |
        Returns the anchoring transaction hash of the given child chain block hash.

        **JSONRPC:** `mainbridge_convertChildChainBlockHashToParentChainTxHash`
      parameters:
        - name: blockHash
          required: true
          in: query
          schema:
            type: string
            format: 32-byte DATA
          description: The child chain block hash.
      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/JsonRpcRequest'
                - $ref: '#/components/schemas/MainbridgeConvertChildChainBlockHashToParentChainTxHashReq'
      responses:
        '200':
          description: The anchoring transaction hash that includes the child chain block information.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/JsonRpcResponse'
                  - $ref: '#/components/schemas/MainbridgeConvertChildChainBlockHashToParentChainTxHashResp'
      x-codeSamples:
        - lang: curl
          label: Curl
          source: |
            curl -X 'POST' \
              'https://api.baobab.klaytn.net:8651/mainbridge/convertChildChainBlockHashToParentChainTxHash' \
              -H 'accept: application/json' \
              -H 'Content-Type: application/json' \
              -d '{
              "method": "mainbridge_convertChildChainBlockHashToParentChainTxHash",
              "id": 1,
              "jsonrpc": "2.0",
              "params": ["0xeadc6a3a29a20c13824b5df1ba05cca1ed248d046382a4f2792aac8a6e0d1880"]
            }'
components:
  schemas:
    JsonRpcRequest:
      type: object
      required:
        - method
        - id
        - jsonrpc
      properties:
        method:
          type: string
          description: Method name
        id:
          type: integer
          default: 1
          format: int64
          description: Request ID, Random or Auto incrementation
        jsonrpc:
          type: string
          default: '2.0'
          description: JSON-RPC Version (2.0)
        params:
          type: array
          items: {}
    MainbridgeGetChildChainIndexingEnabledReq:
      type: object
      required:
        - method
      properties:
        method:
          type: string
          default: mainbridge_getChildChainIndexingEnabled
    ErrorMember:
      type: object
      title: ErrorMember
      required:
        - code
      properties:
        code:
          type: integer
          format: int64
          example: -32700
          description: |
            A Number that indicates the error type that occurred.
            This MUST be an integer.

            | code | message | description |
            |-----|-----|-------|
            | -32700   | Parse error   | invalid JSON was received by the server. An error occurred on the server while parsing the JSON text. |
            |-32602 | Invalid params | Invalid method parameter(s). |
        message:
          type: string
          example: Parse error
          description: |
            A String providing a short description of the error.
            The message SHOULD be limited to a concise single sentence.
        data:
          type: string
          description: |
            A Primitive or Structured value that contains additional information about the error.
            This may be omitted.
            The value of this member is defined by the Server (e.g. detailed error information, nested errors etc.).
    JsonRpcResponse:
      type: object
      required:
        - jsonrpc
        - id
      properties:
        jsonrpc:
          type: string
          default: '2.0'
        id:
          type: integer
          format: int64
        error:
          $ref: '#/components/schemas/ErrorMember'
        result: {}
    MainbridgeGetChildChainIndexingEnabledResp:
      type: object
      properties:
        result:
          type: boolean
          description: true if the indexing was enabled, false otherwise.
          example: '0x0'
    MainbridgeNodeInfoReq:
      type: object
      required:
        - method
      properties:
        method:
          type: string
          default: mainbridge_nodeInfo
    MainbridgeNodeInfoResp:
      type: object
      properties:
        result:
          type: object
          description: the bridge node information.
          example:
            kni: kni://f8a1f0cd1e2bebeece571e4fda16e215218fd4b9bc2eddd924f7cd5b5f950fcec8f4b8cd3851390d1d0bacf1b15e1c4a38c882252e429a28d16eeb6edbacd726@[::]:50505?discport=0
            id: f8a1f0cd1e2bebeece571e4fda16e215218fd4b9bc2eddd924f7cd5b5f950fcec8f4b8cd3851390d1d0bacf1b15e1c4a38c882252e429a28d16eeb6edbacd726
            ip: '::'
            listenAddr: '[::]:50505'
            name: '-2'
            ports:
              discovery: 0
              listener: 50505
            protocols:
              servicechain:
                config:
                  chainId: 2018
                  deriveShaImpl: 0
                  isBFT: true
                  istanbul:
                    ...: null
                  unitPrice: 0
                difficulty: 87860
                genesis: '0x711ce9865492659977abb2758d29f68c2b0c82862d9376f25953579f64f95b58'
                head: '0x0d4b130731f1e7560e4531ac73d55ac8c6daccb178abd86af0d96b7aafded7c5'
                network: 1
    BlockHash:
      title: BlockHash
      type: string
      format: 32-byte DATA
      description: the block hash
    MainbridgeConvertChildChainBlockHashToParentChainTxHashReq:
      type: object
      required:
        - method
        - params
      properties:
        method:
          type: string
          default: mainbridge_convertChildChainBlockHashToParentChainTxHash
        params:
          type: array
          description: The child chain block hash.
          items:
            $ref: '#/components/schemas/BlockHash'
          example:
            - '0xeadc6a3a29a20c13824b5df1ba05cca1ed248d046382a4f2792aac8a6e0d1880'
    MainbridgeConvertChildChainBlockHashToParentChainTxHashResp:
      type: object
      properties:
        result:
          type: string
          format: 32-byte DATA
          description: The anchoring transaction hash that includes the child chain block information.
          example: '0x9a68591c0faa138707a90a7506840c562328aeb7621ac0561467c371b0322d51'
