generatorName: caver-python
outputDir: ./openapi/net
inputSpec: ../../../site/namespace/net-openapi.yaml
projectName: opensdk-python-net
packageName: opensdk_python_net
templateDir: ./template
sortParamsByRequiredFlag: false
globalProperties:
  apiDocs: false
  modelDocs: false
  modelTests: false
  apiTests: true
inlineSchemaNameMappings:
  accountCreated_default_response: AccountCreatedResponse
  getRewards_default_response: GetRewardsResponse
  ethAccounts_default_response: EthAccountsDefaultResponse
  ethBlockNumber_default_response: EthBlockNumberDefaultResponse
  ethCall_default_response: EthCallDefaultResponse