openapi: "3.0.2"
info:
  title: KLAY OPEN API
  version: "1.10.0"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:7151

paths:
  /debug/setMutexProfileFraction:
    post:
      operationId: setMutexProfileFraction
      summary: "[setMutexProfileFraction]"
      description: |
        **JSONRPC:** `debug_setMutexProfileFraction`
      tags:
        - debug

      parameters:
        - name: number
          required: true
          schema:
            type: number
          description: number
          in: query

      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "../../../components/requests/JsonRpcRequest.yaml#/components/schemas/JsonRpcRequest"
                - $ref: "#/components/schemas/setMutexProfileFractionReq"

      responses:
        200:
          description: Set mutex profile fraction
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../../components/responses/JsonRpcResponse.yaml#/components/schemas/JsonRpcResponse"
                  - type: object
                    properties:
                      result:
                        type: string
                        nullable: true
                        example: null


      x-codeSamples:
        - lang: "curl"
          label: "Curl"
          source:
            $ref: "../../../code-samples/curl/klaytnDebug/others/setMutexProfileFraction.sh"
        # - lang: "java"
        #   label: "Java"
        #   source:
        #     $ref: ""
        - lang: "javascript"
          label: "Javascript"
          source:
            $ref: "../../../code-samples/javascript/klaytnDebug/others/setMutexProfileFraction.js"
        # - lang: "python"
        #   label: "Python"
        #   source:
        #     $ref: ""

components:
  schemas:
    setMutexProfileFractionReq:
      type: object
      required:
        - method
        - params
      properties:
        method:
          type: string
          default: 'debug_setMutexProfileFraction'
        params:
          type: array
          items:
            type: number
          description: number
          example: [2]