openapi: "3.0.2"
info:
  title: KLAY OPEN API
  version: "1.10.0"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:7151

paths:
  /klay/decodeAccountKey:
    post:
      operationId: klayDecodeAccountKey
      summary: "[decodeAccountKey] Decodes an RLP encoded account key."
      description: |
        Decodes an RLP encoded account key.

        **JSONRPC:** `klay_decodeAccountKey`
      tags:
        - klay.account

      parameters:
        - name: encodedAccountKey
          in: query
          description: RLP encoded account key
          required: true
          schema:
            type: string
            format: DATA

      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "../../../components/requests/JsonRpcRequest.yaml#/components/schemas/JsonRpcRequest"
                - $ref: "../../../components/schemas/klay/account/DecodeAccountKey.yaml#/components/schemas/KlayDecodeAccountKeyReq"

      responses:
        default:
          description: Decodes an RLP encoded account key.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../../components/responses/JsonRpcResponse.yaml#/components/schemas/JsonRpcResponse"
                  - $ref: "../../../components/schemas/klay/account/DecodeAccountKey.yaml#/components/schemas/KlayDecodeAccountKeyResp"

      externalDocs:
        url: https://docs.klaytn.foundation/content/dapp/json-rpc/api-references/klay/account#klay_decodeaccountkey
        description: Klaytn Docs
      x-codeSamples:
        - lang: "curl"
          label: "Curl"
          source:
            $ref: "../../../code-samples/curl/klay/account/decodeAccountKey.sh"
        # - lang: "java"
        #   label: "Java"
        #   source:
        #     $ref: ""
        #- lang: "javascript"
        #  label: "Javascript"
        #  source:
        #    $ref: ""
        #- lang: "python"
        #  label: "Python"
        #  source:
        #    $ref: ""
