openapi: "3.0.2"
info:
  title: KLAY OPEN API
  version: "1.10.0"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:7151

paths:
  /klay/getAccount:
    post:
      operationId: getAccount
      summary: "[getAccount]"
      description: |
        Returns the account information of a given address. There are two different account types in Klaytn: Externally Owned Account (EOA) and Smart Contract Account. See Klaytn Accounts.

        **JSONRPC:** `klay_getAccount`

        **NOTE:** *In versions earlier than Klaytn v1.7.0, only integer block number, the string "earliest" and "latest" are available.*`
      tags:
        - klay

      parameters:
        - name: address
          in: query
          description: Address
          required: true
          schema:
            $ref: "../../../components/schemas/common/Common.yaml#/components/schemas/Address"
        - name: blockNumberOrHash
          in: query
          description: Integer or hexadecimal block number, or the string "earliest", "latest" or "pending" as in the default block parameter, or block hash.
          required: true
          schema:
            $ref: "../../../components/schemas/common/Common.yaml#/components/schemas/BlockNumberOrHashOrTag"

      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "../../../components/requests/JsonRpcRequest.yaml#/components/schemas/JsonRpcRequest"
                - $ref: "#/components/schemas/KlayGetAccountReq"

      responses:
        200:
          description: Returns the account information of a given address.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../../components/responses/JsonRpcResponse.yaml#/components/schemas/JsonRpcResponse"
                  - $ref: "#/components/schemas/KlayGetAccountResp"

      x-codeSamples:
        - lang: "curl"
          label: "Curl"
          source:
            $ref: "../../../code-samples/curl/klay/account/getAccount.sh"
        - lang: "java"
          label: "Java"
          source:
            $ref: "../../../code-samples/java/src/main/java/opensdk/sdk/apis/klay/account/KlayGetAccountExample.java"
        - lang: "javascript"
          label: "Javascript"
          source:
            $ref: "../../../code-samples/javascript/klay/account/getAccount.js"
        - lang: "python"
          label: "Python"
          source:
            $ref: "../../../code-samples/python/klay/account/getAccount.py"

components:
  schemas:
    KlayGetAccountReq:
      type: object
      required:
        - method
        - params
      properties:
        method:
          type: string
          default: 'klay_getAccount'
        params:
          type: array
          items:
            anyOf:
              - $ref: "../../../components/schemas/common/Common.yaml#/components/schemas/Address"
              - $ref: "../../../components/schemas/common/Common.yaml#/components/schemas/BlockNumberOrHashOrTag"
          example:  ["0x3111a0577f322e8fb54f78d9982a26ae7ca0f722", "latest"]

    KlayGetAccountResp:
      type: object
      properties:
        result:
          type: object
          description: Each account type has different attributes.
          properties:
            accType:
              type: number
              default: 1
            account:
              type: object
              properties:
                balance:
                  type: string
                humanReadable:
                  type: boolean
                key:
                  type: object
                  properties:
                    key:
                      type: object
                      properties:
                        x:
                          type: string
                        y:
                          type: string
                    keyType:
                      type: number
                nonce:
                  type: number
          example:
            {
              accType: 1,
              account: {
                balance: 4985316100000000000,
                humanReadable: false,
                key: {
                  key: {
                    x: "0x230037a99462acd829f317d0ce5c8e2321ac2951de1c1b1a18f9af5cff66f0d7",
                    y: "0x18a7fb1b9012d2ac87bc291cbf1b3b2339356f1ce7669ae68405389be7f8b3b6"
                  },
                  keyType: 2
                },
                nonce: 11
              }
            }
