openapi: "3.0.2"
info:
  title: KLAY OPEN API
  version: "1.10.0"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:7151

paths:
  /admin/exportChain:
    post:
      operationId: exportChain
      summary: "[exportChain]"
      description: |
        The exportChain is an administrative method that exports the blockchain to a file.

        **JSONRPC:** `admin_exportChain`

      tags:
        - admin

      parameters:
        - name: fileName
          required: true
          schema:
            type: string
          description: the fully qualified path to the file where the blockchain must be exported.
          in: query

      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "../../components/requests/JsonRpcRequest.yaml#/components/schemas/JsonRpcRequest"
                - $ref: "#/components/schemas/ExportChainReq"

      responses:
        200:
          description: true if chain was exported, false if not.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../components/responses/JsonRpcResponse.yaml#/components/schemas/JsonRpcResponse"
                  - $ref: "#/components/schemas/ExportChainResp"

      x-codeSamples:
        - lang: "curl"
          label: "Curl"
          source:
            $ref: "../../code-samples/curl/admin/exportChain.sh"
        # - lang: "java"
        #   label: "Java"
        #   source:
        #     $ref: ""
        - lang: "javascript"
          label: "Javascript"
          source:
           $ref: "../../code-samples/javascript/admin/exportChainApi.js"
        - lang: "python"
           label: "Python"
           source:
             $ref: "../../code-samples/python/admin/exportChain.py"

components:
  schemas:
    ExportChainReq:
      type: object
      required:
        - method
        - params
      properties:
        method:
          type: string
          default: 'admin_exportChain'
        params:
          type: array
          description: the fully qualified path to the file where the blockchain must be exported.
          items:
            title: FileName
            type: string
          example: ["/tmp/chain.txt"]

    ExportChainResp:
      type: object
      properties:
        result:
          type: boolean
          description: true if chain was exported, false if not.
          example: true
      
    


