openapi: "3.0.2"
info:
  title: KLAY OPEN API
  version: "1.10.0"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:7151

paths:
  /admin/stopStateMigration:
    post:
      operationId: stopStateMigration
      summary: "[stopStateMigration]"
      description: |
        The stopStateMigration is an administrative method that stops the currently running state migration. This method takes no parameters and returns null or an error whether the state migration was stopped or not.       
       
        **JSONRPC:** `admin_stopStateMigration`

      tags:
        - admin
  
      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "../../components/requests/JsonRpcRequest.yaml#/components/schemas/JsonRpcRequest"
                - $ref: "#/components/schemas/StopStateMigrationReq"

      responses:
        200:
          description: null if the state migration is stopped, or an error if not.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../components/responses/JsonRpcResponse.yaml#/components/schemas/JsonRpcResponse"
                  - $ref: "#/components/schemas/StopStateMigrationResp"

      x-codeSamples:
        - lang: "curl"
          label: "Curl"
          source:
            $ref: "../../code-samples/curl/admin/stopStateMigration.sh"
        # - lang: "java"
        #   label: "Java"
        #   source:
        #     $ref: ""
        # - lang: "javascript"
        #   label: "Javascript"
        #   source:
        #    $ref: ""
        # - lang: "python"
        #   label: "Python"
        #   source:
        #     $ref: ""

components:
  schemas:
    StopStateMigrationReq:
      type: object
      required:
        - method
      properties:
        method:
          type: string
          default: 'admin_stopStateMigration'

    StopStateMigrationResp:
      description: null if the state migration is stopped, or an error if not.
      type: object
      properties:
        result:
          type: string
          example: null





