openapi: "3.0.2"
info:
  title: KLAYTN OPEN API
  version: "1.10.0"
  contact:
    name: API support
    url: https://forum.klaytn.foundation/
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
tags:
  - name: debug
    description: API for debug namespace
x-tagGroups:
  - name: Debug
    tags:
      - debug
  - name: Models
    tags:
      - RewardSpec
servers:
  - url: http://localhost:7151
  - url: https://api.baobab.klaytn.net:8651
  - url: https://public-en-cypress.klaytn.net
paths:
  # debug/logging:
  /debug/logging/setVMLogTarget:
    $ref: ./logging/setVMLogTarget.yaml#/paths/~1debug~1setVMLogTarget

  # debug/blockchainInspection:
  /debug/blockchainInspection/preimage:
    $ref: ./blockchainInspection/preimage.yaml#/paths/~1debug~1preimage
  /debug/blockchainInspection/dumpBlock:
    $ref: ./blockchainInspection/dumpBlock.yaml#/paths/~1debug~1dumpBlock
  /debug/blockchainInspection/dumpStateTrie:
    $ref: ./blockchainInspection/dumpStateTrie.yaml#/paths/~1debug~1dumpStateTrie
  /debug/blockchainInspection/getBlockRlp:
    $ref: ./blockchainInspection/getBlockRlp.yaml#/paths/~1debug~1getBlockRlp
  /debug/blockchainInspection/getModifiedAccountsByNumber:
    $ref: ./blockchainInspection/getModifiedAccountsByNumber.yaml#/paths/~1debug~1getModifiedAccountsByNumber
  /debug/blockchainInspection/getModifiedAccountsByHash:
    $ref: ./blockchainInspection/getModifiedAccountsByHash.yaml#/paths/~1debug~1getModifiedAccountsByHash
    
