generatorName: caver-java
outputDir: ./openapi/debug
inputSpec: ../../../site/namespace/debug-openapi.yaml
groupId: klaytn.foundation
artifactId: web3api-debug
artifactVersion: v1.10.0
library: retrofit2
templateDir: ./template
globalProperties:
  apiDocs: false
  modelDocs: false
  apiTests: false
  modelTests: false
additionalProperties:
  # This open is related json nullable, so it should be off.
  openApiNullable: false
  apiPackage: org.web3j.protocol.klaytn.core
  modelPackage: org.web3j.protocol.klaytn.core.method.response
typeMappings:
  double: java.math.BigInteger
  Long: long
  ErrorMember: Error
importMappings:
  GetRewardsDefaultResponse: org.web3j.protocol.klaytn.core.method.response.GetRewardsResponse
  AnyOfstring: java.util.Objects
  Error: java.util.Objects
inlineSchemaNameMappings:
  accountCreated_default_response: AccountCreatedResponse
  getRewards_default_response: GetRewardsResponse
