openapi: "3.0.2"
info:
  title: KLAYTN OPEN API
  version: "1.10.0"
  contact:
    name: API support
    url: https://forum.klaytn.foundation/
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
tags:
  - name: klay
    description: klaytn node API
  - name: account
    description: klaytn account API
  - name: governance
    description: klaytn governance API
  - name: eth
    description: API for ethereum namespace
#  - name: RewardSpec
#    description: |
#      <SchemaDefinition schemaRef="#/components/schemas/RewardSpec" />
x-tagGroups:
  - name: Eth
    tags:
      - eth.block
      - eth.account
      - eth.transaction
  - name: Klay
    tags:
      - klay.account
      - klay.block
      - klay.configuration
      - klay.gas
      - klay.transaction
      - klay.filter
  - name: Models
    tags:
      - RewardSpec
servers:
  - url: http://localhost:7151
  - url: https://api.baobab.klaytn.net:8651
  - url: https://public-en-cypress.klaytn.net
paths:
  # klay/account
  /klay/account/accountCreated:
    $ref: ./paths/klay/account/accountCreated.yaml#/paths/~1klay~1accountCreated
  /klay/account/accounts:
    $ref: ./paths/klay/account/accounts.yaml#/paths/~1klay~1accounts
  /klay/account/decodeAccountKey:
    $ref: ./paths/klay/account/decodeAccountKey.yaml#/paths/~1klay~1decodeAccountKey
  /klay/account/getAccountKey:
    $ref: ./paths/klay/account/getAccountKey.yaml#/paths/~1klay~1getAccountKey
  /klay/account/getCode:
    $ref: ./paths/klay/account/getCode.yaml#/paths/~1klay~1getCode
  /klay/account/encodeAccountKey:
    $ref: ./paths/klay/account/encodeAccountKey.yaml#/paths/~1klay~1encodeAccountKey
  /klay/account/getAccount:
    $ref: ./paths/klay/account/getAccount.yaml#/paths/~1klay~1getAccount
  /klay/account/getBalance:
    $ref: ./paths/klay/account/getBalance.yaml#/paths/~1klay~1getBalance

  # klay/block
  /klay/block/blockNumber:
    $ref: ./paths/klay/block/blockNumber.yaml#/paths/~1klay~1blockNumber
  /klay/block/getBlockByHash:
    $ref: ./paths/klay/block/getBlockByHash.yaml#/paths/~1klay~1getBlockByHash
  /klay/block/getBlockReceipts:
    $ref: ./paths/klay/block/getBlockReceipts.yaml#/paths/~1klay~1getBlockReceipts
  /klay/block/getBlockTransactionCountByNumber:
    $ref: ./paths/klay/block/getBlockTransactionCountByNumber.yaml#/paths/~1klay~1getBlockTransactionCountByNumber
  /klay/block/getBlockWithConsensusInfoByNumber:
    $ref: ./paths/klay/block/getBlockWithConsensusInfoByNumber.yaml#/paths/~1klay~1getBlockWithConsensusInfoByNumber
  /klay/block/getCommittee:
    $ref: ./paths/klay/block/getCommittee.yaml#/paths/~1klay~1getCommittee
  /klay/block/getCommitteeSize:
    $ref: ./paths/klay/block/getCommitteeSize.yaml#/paths/~1klay~1getCommitteeSize
  /klay/block/getCouncilSize:
    $ref: ./paths/klay/block/getCouncilSize.yaml#/paths/~1klay~1getCouncilSize
  /klay/block/getBlockByNumber:
    $ref: ./paths/klay/block/getBlockByNumber.yaml#/paths/~1klay~1getBlockByNumber
  /klay/block/getBlockTransactionCountByHash:
    $ref: ./paths/klay/block/getBlockTransactionCountByHash.yaml#/paths/~1klay~1getBlockTransactionCountByHash
  /klay/block/getHeaderByNumber:
    $ref: ./paths/klay/block/getHeaderByNumber.yaml#/paths/~1klay~1getHeaderByNumber
  /klay/getRewards:
    $ref: ./paths/klay/block/getRewards.yaml#/paths/~1klay~1getRewards


  # klay/transaction
  /klay/transaction/call:
    $ref: ./paths/klay/transaction/call.yaml#/paths/~1klay~1call
  /klay/transaction/getDecodedAnchoringTransactionByHash:
    $ref: ./paths/klay/transaction/getDecodedAnchoringTransactionByHash.yaml#/paths/~1klay~1getDecodedAnchoringTransactionByHash
  /klay/transaction/estimateGas:
    $ref: ./paths/klay/transaction/estimateGas.yaml#/paths/~1klay~1estimateGas

  # klay/configuration
  /klay/configuration/chainID:
    $ref: ./paths/klay/configuration/chainID.yaml#/paths/~1klay~1chainID
  /klay/configuration/clientVersion:
    $ref: ./paths/klay/configuration/clientVersion.yaml#/paths/~1klay~1clientVersion
  /klay/configuration/gasPriceAt:
    $ref: ./paths/klay/configuration/gasPriceAt.yaml#/paths/~1klay~1gasPriceAt
  /klay/configuration/gasPrice:
    $ref: ./paths/klay/configuration/gasPrice.yaml#/paths/~1klay~1gasPrice

  # klay/filter
  /klay/filter/getFilterLogs:
    $ref: ./paths/klay/filter/getFilterLogs.yaml#/paths/~1klay~1getFilterLogs

  # klay/gas
  /klay/gas/feeHistory:
    $ref: ./paths/klay/gas/feeHistory.yaml#/paths/~1klay~1feeHistory

  # eth/account
  /eth/account/accounts:
    $ref: ./paths/eth/account/accounts.yaml#/paths/~1eth~1accounts

  # eth/block
  /eth/block/blockNumber:
    $ref: ./paths/eth/block/blockNumber.yaml#/paths/~1eth~1blockNumber

  # eth/transaction
  /eth/transaction/call:
    $ref: ./paths/eth/transaction/call.yaml#/paths/~1eth~1call
