openapi: "3.0.2"
info:
  title: KLAYTN OPEN API
  version: "1.10.0"
  contact:
    name: API support
    url: https://forum.klaytn.foundation/
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
tags:
  - name: klay
    description: klaytn node API
  - name: account
    description: klaytn account API
  - name: governance
    description: klaytn governance API
  - name: eth
    description: API for ethereum namespace
#  - name: RewardSpec
#    description: |
#      <SchemaDefinition schemaRef="#/components/schemas/RewardSpec" />
x-tagGroups:
  - name: Eth
    tags:
      - eth.block
      - eth.account
      - eth.transaction
  - name: Klay
    tags:
      - klay
      - klay.account
      - klay.block
      - klay.configuration
      - klay.gas
      - klay.transaction
  - name: Models
    tags:
      - RewardSpec
servers:
  - url: http://localhost:7151
  - url: https://api.baobab.klaytn.net:8651
  - url: https://public-en-cypress.klaytn.net
paths:
  /klay/getRewards:
    $ref: ./paths/klay/rewards.yaml#/paths/~1klay~1getRewards

  # klay/account
  /klay/account/accountCreated:
    $ref: ./paths/klay/account/accountCreated.yaml#/paths/~1klay~1accountCreated
  /klay/account/accounts:
    $ref: ./paths/klay/account/accounts.yaml#/paths/~1klay~1accounts
  /klay/account/decodeAccountKey:
    $ref: ./paths/klay/account/decodeAccountKey.yaml#/paths/~1klay~1decodeAccountKey
  /klay/account/getAccountKey:
    $ref: ./paths/klay/account/getAccountKey.yaml#/paths/~1klay~1getAccountKey

  # klay/block
  /klay/block/blockNumber:
    $ref: ./paths/klay/block/blockNumber.yaml#/paths/~1klay~1blockNumber
  /klay/block/getBlockByHash:
    $ref: ./paths/klay/block/getBlockByHash.yaml#/paths/~1klay~1getBlockByHash

  # klay/transaction
  /klay/transaction/call:
    $ref: ./paths/klay/transaction/call.yaml#/paths/~1klay~1call

  # klay/configuration
  /klay/configuration/chainID:
    $ref: ./paths/klay/configuration/chainID.yaml#/paths/~1klay~1chainID
  /klay/configuration/clientVersion:
    $ref: ./paths/klay/configuration/clientVersion.yaml#/paths/~1klay~1clientVersion
  /klay/configuration/gasPriceAt:
    $ref: ./paths/klay/configuration/gasPriceAt.yaml#/paths/~1klay~1gasPriceAt

  # klay/gas
  /klay/gas/feeHistory:
    $ref: ./paths/klay/gas/feeHistory.yaml#/paths/~1klay~1feeHistory

  # eth/account
  /eth/account/accounts:
    $ref: ./paths/eth/account/accounts.yaml#/paths/~1eth~1accounts

  # eth/block
  /eth/block/blockNumber:
    $ref: ./paths/eth/block/blockNumber.yaml#/paths/~1eth~1blockNumber

  # eth/transaction
  /eth/transaction/call:
    $ref: ./paths/eth/transaction/call.yaml#/paths/~1eth~1call
