openapi: "3.0.2"
info:
  title: KLAYTN OPEN API
  version: "1.10.0"
  contact:
    name: API support
    url: https://forum.klaytn.foundation/
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
tags:
  - name: klay
    description: klaytn node API
  - name: account
    description: klaytn account API
  - name: governance
    description: klaytn governance API
  - name: eth
    description: API for ethereum namespace
#  - name: RewardSpec
#    description: |
#      <SchemaDefinition schemaRef="#/components/schemas/RewardSpec" />
x-tagGroups:
  - name: Eth
    tags:
      - eth
  - name: Klay
    tags:
      - klay
  - name: Models
    tags:
      - RewardSpec
servers:
  - url: http://localhost:7151
  - url: https://api.baobab.klaytn.net:8651
  - url: https://public-en-cypress.klaytn.net
paths:
  # klay/account
  /klay/account/accountCreated:
    $ref: ./paths/klay/account/accountCreated.yaml#/paths/~1klay~1accountCreated
  /klay/account/accounts:
    $ref: ./paths/klay/account/accounts.yaml#/paths/~1klay~1accounts
  /klay/account/decodeAccountKey:
    $ref: ./paths/klay/account/decodeAccountKey.yaml#/paths/~1klay~1decodeAccountKey
  /klay/account/getAccountKey:
    $ref: ./paths/klay/account/getAccountKey.yaml#/paths/~1klay~1getAccountKey
  /klay/account/getCode:
    $ref: ./paths/klay/account/getCode.yaml#/paths/~1klay~1getCode
  /klay/account/encodeAccountKey:
    $ref: ./paths/klay/account/encodeAccountKey.yaml#/paths/~1klay~1encodeAccountKey
  /klay/account/getAccount:
    $ref: ./paths/klay/account/getAccount.yaml#/paths/~1klay~1getAccount
  /klay/account/getBalance:
    $ref: ./paths/klay/account/getBalance.yaml#/paths/~1klay~1getBalance
  /klay/account/sign:
    $ref:  ./paths/klay/account/sign.yaml#/paths/~1klay~1sign
  /klay/account/getTransactionCount:
    $ref: ./paths/klay/account/getTransactionCount.yaml#/paths/~1klay~1getTransactionCount
  /klay/account/isContractAccount:
    $ref: ./paths/klay/account/isContractAccount.yaml#/paths/~1klay~1isContractAccount

  # klay/block
  /klay/block/blockNumber:
    $ref: ./paths/klay/block/blockNumber.yaml#/paths/~1klay~1blockNumber
  /klay/block/getBlockByHash:
    $ref: ./paths/klay/block/getBlockByHash.yaml#/paths/~1klay~1getBlockByHash
  /klay/block/getBlockReceipts:
    $ref: ./paths/klay/block/getBlockReceipts.yaml#/paths/~1klay~1getBlockReceipts
  /klay/block/getBlockTransactionCountByNumber:
    $ref: ./paths/klay/block/getBlockTransactionCountByNumber.yaml#/paths/~1klay~1getBlockTransactionCountByNumber
  /klay/block/getBlockWithConsensusInfoByNumber:
    $ref: ./paths/klay/block/getBlockWithConsensusInfoByNumber.yaml#/paths/~1klay~1getBlockWithConsensusInfoByNumber
  /klay/block/getCommittee:
    $ref: ./paths/klay/block/getCommittee.yaml#/paths/~1klay~1getCommittee
  /klay/block/getCommitteeSize:
    $ref: ./paths/klay/block/getCommitteeSize.yaml#/paths/~1klay~1getCommitteeSize
  /klay/block/getCouncil:
    $ref: ./paths/klay/block/getCouncil.yaml#/paths/~1klay~1getCouncil
  /klay/block/getCouncilSize:
    $ref: ./paths/klay/block/getCouncilSize.yaml#/paths/~1klay~1getCouncilSize
  /klay/block/getBlockByNumber:
    $ref: ./paths/klay/block/getBlockByNumber.yaml#/paths/~1klay~1getBlockByNumber
  /klay/block/getBlockTransactionCountByHash:
    $ref: ./paths/klay/block/getBlockTransactionCountByHash.yaml#/paths/~1klay~1getBlockTransactionCountByHash
  /klay/block/getHeaderByNumber:
    $ref: ./paths/klay/block/getHeaderByNumber.yaml#/paths/~1klay~1getHeaderByNumber
  /klay/block/getHeaderByHash:
    $ref: ./paths/klay/block/getHeaderByHash.yaml#/paths/~1klay~1getHeaderByHash
  /klay/block/getRewards:
    $ref: ./paths/klay/block/getRewards.yaml#/paths/~1klay~1getRewards
  /klay/block/getStorageAt:
    $ref: ./paths/klay/block/getStorageAt.yaml#/paths/~1klay~1getStorageAt
  /klay/block/syncing:
    $ref: ./paths/klay/block/syncing.yaml#/paths/~1klay~1syncing

  # klay/transaction
  /klay/transaction/call:
    $ref: ./paths/klay/transaction/call.yaml#/paths/~1klay~1call
  /klay/transaction/getDecodedAnchoringTransactionByHash:
    $ref: ./paths/klay/transaction/getDecodedAnchoringTransactionByHash.yaml#/paths/~1klay~1getDecodedAnchoringTransactionByHash
  /klay/transaction/estimateGas:
    $ref: ./paths/klay/transaction/estimateGas.yaml#/paths/~1klay~1estimateGas
  /klay/transaction/getTransactionByBlockNumberAndIndex:
    $ref: ./paths/klay/transaction/getTransactionByBlockNumberAndIndex.yaml#/paths/~1klay~1getTransactionByBlockNumberAndIndex
  /klay/transaction/getTransactionBySenderTxHash:
    $ref: ./paths/klay/transaction/getTransactionBySenderTxHash.yaml#/paths/~1klay~1getTransactionBySenderTxHash
  /klay/transaction/getTransactionByBlockHashAndIndex:
    $ref: ./paths/klay/transaction/getTransactionByBlockHashAndIndex.yaml#/paths/~1klay~1getTransactionByBlockHashAndIndex
  /klay/transaction/getTransactionByHash:
    $ref: ./paths/klay/transaction/getTransactionByHash.yaml#/paths/~1klay~1getTransactionByHash
  /klay/transaction/getTransactionReceipt:
    $ref: ./paths/klay/transaction/getTransactionReceipt.yaml#/paths/~1klay~1getTransactionReceipt
  /klay/transaction/sendRawTransaction:
    $ref: ./paths/klay/transaction/sendRawTransaction.yaml#/paths/~1klay~1sendRawTransaction
  /klay/transaction/estimateComputationCost:
    $ref: ./paths/klay/transaction/estimateComputationCost.yaml#/paths/~1klay~1estimateComputationCost
  /klay/transaction/getTransactionReceiptBySenderTxHash:
    $ref: ./paths/klay/transaction/getTransactionReceiptBySenderTxHash.yaml#/paths/~1klay~1getTransactionReceiptBySenderTxHash
  /klay/transaction/sendTransaction:
    $ref: ./paths/klay/transaction/sendTransaction.yaml#/paths/~1klay~1sendTransaction
  /klay/transaction/sendTransactionAsFeePayer:
    $ref: ./paths/klay/transaction/sendTransactionAsFeePayer.yaml#/paths/~1klay~1sendTransactionAsFeePayer
  /klay/transaction/signTransaction:
    $ref: ./paths/klay/transaction/signTransaction.yaml#/paths/~1klay~1signTransaction
  /klay/transaction/signTransactionAsFeePayer:
    $ref: ./paths/klay/transaction/signTransactionAsFeePayer.yaml#/paths/~1klay~1signTransactionAsFeePayer


  # klay/configuration
  /klay/configuration/chainID:
    $ref: ./paths/klay/configuration/chainID.yaml#/paths/~1klay~1chainID
  /klay/configuration/clientVersion:
    $ref: ./paths/klay/configuration/clientVersion.yaml#/paths/~1klay~1clientVersion
  /klay/configuration/gasPriceAt:
    $ref: ./paths/klay/configuration/gasPriceAt.yaml#/paths/~1klay~1gasPriceAt
  /klay/configuration/gasPrice:
    $ref: ./paths/klay/configuration/gasPrice.yaml#/paths/~1klay~1gasPrice
  /klay/configuration/isParallelDBWrite:
    $ref: ./paths/klay/configuration/isParallelDBWrite.yaml#/paths/~1klay~1isParallelDBWrite
  /klay/configuration/isSenderTxHashIndexingEnabled:
    $ref: ./paths/klay/configuration/isSenderTxHashIndexingEnabled.yaml#/paths/~1klay~1isSenderTxHashIndexingEnabled
  /klay/configuration/maxPriorityFeePerGas:
    $ref: ./paths/klay/configuration/maxPriorityFeePerGas.yaml#/paths/~1klay~1maxPriorityFeePerGas
  /klay/configuration/protocolVersion:
    $ref: ./paths/klay/configuration/protocolVersion.yaml#/paths/~1klay~1protocolVersion
  /klay/configuration/rewardBase:
    $ref: ./paths/klay/configuration/rewardBase.yaml#/paths/~1klay~1rewardBase

  # klay/filter
  /klay/filter/getFilterChanges:
    $ref: ./paths/klay/filter/getFilterChanges.yaml#/paths/~1klay~1getFilterChanges
  /klay/filter/getFilterLogs:
    $ref: ./paths/klay/filter/getFilterLogs.yaml#/paths/~1klay~1getFilterLogs
  /klay/filter/newBlockFilter:
    $ref: ./paths/klay/filter/newBlockFilter.yaml#/paths/~1klay~1newBlockFilter
  /klay/filter/newPendingTransactionFilter:
    $ref: ./paths/klay/filter/newPendingTransactionFilter.yaml#/paths/~1klay~1newPendingTransactionFilter
  /klay/filter/newFilter:
    $ref: ./paths/klay/filter/newFilter.yaml#/paths/~1klay~1newFilter
  /klay/filter/uninstallFilter:
    $ref: ./paths/klay/filter/uninstallFilter.yaml#/paths/~1klay~1uninstallFilter

  # klay/gas
  /klay/gas/feeHistory:
    $ref: ./paths/klay/gas/feeHistory.yaml#/paths/~1klay~1feeHistory

  # klay/miscellaneous
  /klay/miscellaneous/sha3:
    $ref: ./paths/klay/miscellaneous/sha3.yaml#/paths/~1klay~1sha3

  # klay/other
  /klay/createAccessList:
    $ref: ./paths/klay/other/createAccessList.yaml#/paths/~1klay~1createAccessList
  /klay/getRawTransactionByBlockHashAndIndex:
    $ref: ./paths/klay/other/getRawTransactionByBlockHashAndIndex.yaml#/paths/~1klay~1getRawTransactionByBlockHashAndIndex
  /klay/getRawTransactionByHash:
    $ref: ./paths/klay/other/getRawTransactionByHash.yaml#/paths/~1klay~1getRawTransactionByHash
  /klay/nodeAddress:
    $ref: ./paths/klay/other/nodeAddress.yaml#/paths/~1klay~1nodeAddress

  # eth/account
  /eth/account/accounts:
    $ref: ./paths/eth/account/accounts.yaml#/paths/~1eth~1accounts
  /eth/account/getBalance:
    $ref: ./paths/eth/account/getBalance.yaml#/paths/~1eth~1getBalance
  /eth/account/getCode:
    $ref: ./paths/eth/account/getCode.yaml#/paths/~1eth~1getCode

  # eth/block
  /eth/block/blockNumber:
    $ref: ./paths/eth/block/blockNumber.yaml#/paths/~1eth~1blockNumber
  /eth/block/getBlockByHash:
    $ref: ./paths/eth/block/getBlockByHash.yaml#/paths/~1eth~1getBlockByHash
  /eth/block/getBlockByNumber:
    $ref: ./paths/eth/block/getBlockByNumber.yaml#/paths/~1eth~1getBlockByNumber
  /eth/block/getBlockTransactionCountByHash:
    $ref: ./paths/eth/block/getBlockTransactionCountByHash.yaml#/paths/~1eth~1getBlockTransactionCountByHash
  /eth/block/getHeaderByNumber:
    $ref: ./paths/eth/block/getHeaderByNumber.yaml#/paths/~1eth~1getHeaderByNumber
  /eth/block/getHeaderByHash:
    $ref: ./paths/eth/block/getHeaderByHash.yaml#/paths/~1eth~1getHeaderByHash
  /eth/block/getStorageAt:
    $ref: ./paths/eth/block/getStorageAt.yaml#/paths/~1eth~1getStorageAt

  # eth/transaction
  /eth/transaction/call:
    $ref: ./paths/eth/transaction/call.yaml#/paths/~1eth~1call
  /eth/transaction/getTransactionByBlockHashAndIndex:
    $ref: ./paths/eth/transaction/getTransactionByBlockHashAndIndex.yaml#/paths/~1eth~1getTransactionByBlockHashAndIndex

  # eth/config
  /eth/config/chainID:
    $ref: ./paths/eth/config/chainId.yaml#/paths/~1eth~1chainId
  /eth/config/gasPrice:
    $ref: ./paths/eth/config/gasPrice.yaml#/paths/~1eth~1gasPrice
  /eth/config/coinbase:
    $ref: ./paths/eth/config/coinbase.yaml#/paths/~1eth~1coinbase

  # eth/gas
  /eth/gas/feeHistory:
    $ref: ./paths/eth/gas/feeHistory.yaml#/paths/~1eth~1feeHistory
  /eth/transaction/estimateGas:
    $ref: ./paths/eth/transaction/estimateGas.yaml#/paths/~1eth~1estimateGas
  /eth/transaction/fillTransaction:
    $ref: ./paths/eth/transaction/fillTransaction.yaml#/paths/~1eth~1fillTransaction

  # eth/filter
  /eth/filter/getFilterLogs:
    $ref: ./paths/eth/filter/getFilterLogs.yaml#/paths/~1eth~1getFilterLogs
  /eth/filter/getFilterChanges:
    $ref: ./paths/eth/filter/getFilterChanges.yaml#/paths/~1eth~1getFilterChanges
