# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: NPM publish on release

on:
  push:
    branches:
      - dev

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.7
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build & deploy python sdk
        run: |
          java -version && pip --version &&\
          cd web3rpc/rpc-specs && npm install && sudo sh -x generate-namespace.sh && cd - && \
          cd web3rpc/codegen && gradle wrapper && sudo sh -x ./deploy.sh && cd - &&\
          cd web3rpc/sdk/client/python && sudo sh -x python-generate.sh && cd -