name: "SDK publish on release - Ether"
on:
  workflow_run:
    workflows: ["testing"]
    branches: [devops/update-cicd-pipeline]
    types:
      - completed
jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "11"
      - name: generate code and namespace
        shell: bash
        run: |
          cd web3rpc/codegen && gradle wrapper && gradle wrapper clean :deployJar && cd - &&\
          cd web3rpc/rpc-specs && npm install && bash -x generate-namespace.sh && cd -

      - name: generate ethers-ext sdk
        shell: bash
        run: |
          cd ethers-ext && npm install && npm run build && cd -