# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: SDK publish on release

on:
  push:
    branches:
      - dev

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: generate code and namespace
        shell: bash
        run: |
          cd web3rpc/rpc-specs && npm install && bash -x generate-namespace.sh && cd - && \
          cd web3rpc/codegen && gradle wrapper && gradle wrapper clean :deployJar && cd -
      - name: generate python sdk
        shell: bash
        run: |
          cd web3py-ext &&\
          python -m pip install build wheel twine &&\     
          python setup.py bdist_wheel
          cd -
#      - name: generate java sdk
#        shell: bash
#        run: |
#          cd web3rpc/sdk/client/java && bash -x java-generate.sh && cd -
#      - name: generate js sdk
#        shell: bash
#        run: |
#          cd web3rpc/sdk/client/javascript && bash -x javascript-generate.sh && cd -
      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages-dir: web3py-ext/dist
