name: SDK publish on release - Java
on:
  workflow_run:
    workflows: ["testing"]
    branches: [main]
    types:
      - completed

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: generate code and namespace
        shell: bash
        run: |
          cd web3rpc/codegen && gradle wrapper && gradle wrapper clean :deployJar && cd - &&\
          cd web3rpc/rpc-specs && npm install && bash -x generate-namespace.sh && cd -

      - name: generate java sdk
        shell: bash
        run: |
          cd web3rpc/sdk/client/java && bash -x java-generate.sh  && cd -
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          ORG_GRADLE_PROJECT_SIGNINGPASSWORD: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGPASSWORD }}
          ORG_GRADLE_PROJECT_SIGNINGKEY: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGKEY }}

      - name: Publish web3rpc-java package
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publish
          build-root-directory: web3rpc/sdk/client/java/openapi
          gradle-version: release-candidate
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          ORG_GRADLE_PROJECT_SIGNINGPASSWORD: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGPASSWORD }}
          ORG_GRADLE_PROJECT_SIGNINGKEY: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGKEY }}

      - name: Publish web3j-ext
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publish
          build-root-directory: web3j-ext/web3j-ext
          gradle-version: release-candidate
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          ORG_GRADLE_PROJECT_SIGNINGPASSWORD: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGPASSWORD }}
          ORG_GRADLE_PROJECT_SIGNINGKEY: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGKEY }}
