openapi: "3.0.2"
info:
  title: Klay Open API
  version: "1.10.0"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:7151

components:
  schemas:
    EthAccountsResp:
      type: object
      properties:
        result:
          type: array
          items:
            type: string
            format: 20-byte DATA
            readOnly: true
            example: "0xc94770007dda54cF92009BFF0dE90c06F603a09f"


paths:
  /eth/accounts:
    post:
      summary: "[accounts] Returns a list of addresses owned by client"
      tags:
        - eth
      operationId: accounts
      description: |
        Returns a list of addresses owned by client
        
        **JSONRPC:** `eth_accounts`

      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "../../../components/requests/JsonRpcRequest.yaml#/components/schemas/JsonRpcRequest"
                - type: object
                  properties:
                    method:
                      type: string
                      default: eth_accounts

      responses:
        200:
          description: Addresses owned by the client
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../../components/responses/JsonRpcResponse.yaml#/components/schemas/JsonRpcResponse"
                  - EthAccountsResp

      externalDocs:
        url: https://docs.klaytn.foundation/content/dapp/json-rpc/api-references/eth/account#eth_accounts
        description: Klaytn Docs

      x-codeSamples:
        - lang: "curl"
          label: "Curl"
          source:
            $ref: "../../../code-samples/curl/eth/account/accounts.sh"
        - lang: "java"
          label: "Java"
          source:
            $ref: "../../../code-samples/java/src/main/kotlin/com/klaytn/example/account/EthAccountsExample.kt"
        - lang: "javascript"
          label: "Javascript"
          source:
            $ref: "../../../code-samples/javascript/eth/account/accounts.js"
        #- lang: "python"
        #  label: "Python"
        #  source:
        #    $ref: ""
